Add support for YugabyteDB
sqitchers/sqitch pull request #635
Opened 2022-05-28 19:48 UTC by theory

Works great with the Postgres engine except for locks. So detect that it's Yugabyte and don't create the locks if it is. Change the handling of the `lock_sql` option in the database tests to take a code reference instead of a hash reference, and only return the locking instructions in `t/pg.t` if the engine is not Yugabyte. Mention the Yugabyte support here and there.

2022-06-04 21:33 UTC, autarch requested changes
This looks good to me. Just a few typos in comments.

2022-06-04 21:33 UTC, autarch commented on Changes
> +       not supported are locking, so users need to manually sure tha only one
"ensure that"

2022-06-04 21:33 UTC, autarch commented on lib/App/Sqitch/Engine/pg.pm
> +                    # Determine the provider. Yugabyte says this is the righ tway to do it.
"right way"

2022-06-04 21:50 UTC, theory commented
Thanks @autarch, fixed those in b901fe8c.

2022-06-04 22:13 UTC, merged

2024-11-21 17:28 UTC, stefanoric commented
Hey @theory how is this supposed to be used? I am testing sqitch with yugabyte and still getting the advisory lock error.

```
$> sqitch deploy db:yugabyte://yugabyte@127.0.0.11:5433/yugabyte
ERROR:  advisory locks are not yet implemented
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/3642. React with thumbs up to raise its priority

$> ✗ sqitch --version
sqitch (App::Sqitch) v1.4.1

$> brew info yugabytedb
==> yugabyte/tap/yugabytedb: stable 2024.1.3.0

2024-11-21 17:41 UTC, stefanoric commented
I get this:
```
 PostgreSQL 11.2-YB-2.21.0.0-b0 on x86_64-apple-darwin21.6.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit
```

2024-11-21 18:47 UTC, theory commented
Hrm. What's the output of

```sql
SELECT split_part(version(), ' ', 2);
```

It _should_ be `11.2-YB-2.21.0.0-b0`, in which case `$v =~ /-YB-/` should match.

2024-11-22 09:13 UTC, stefanoric commented
Yes, this is what I get:

```
yugabyte@yugabyte=# select split_part(version(), ' ',2);
     split_part
─────────────────────
 11.2-YB-2.21.0.0-b0
(1 row)
```

2024-11-22 11:14 UTC, FranckPachot commented
@theory  At that time, I think the error was a warning, so maybe the provider check never worked.
@stefanoric As a workaround, it is possible to ignore the error with `set yb_silence_advisory_locks_not_supported_error to true`

2024-11-22 13:45 UTC, stefanoric commented
@FranckPachot thank you for chiming in. I am not entirely sure where that statement is meant to be issued. I don't have a session open on the database when the sqitch scripts run. I have tried setting this as my first DDL statement, but it's not effective (likely sqitch is trying to create the lock _before_ starting to run the schema creation steps).

2024-11-22 15:41 UTC, theory commented
Oh, has calling `pg_try_advisory_lock()` changed from a warning to an error? If so, this bit probably needs updating:

https://github.com/sqitchers/sqitch/blob/a7dfdb3b16979bf9cdd414af10eb1a7236a36066/lib/App/Sqitch/Engine/pg.pm#L294-L298

It already skips calling `pg_advisory_lock()` a few lines below:

https://github.com/sqitchers/sqitch/blob/a7dfdb3b16979bf9cdd414af10eb1a7236a36066/lib/App/Sqitch/Engine/pg.pm#L305-L309

2024-11-22 15:43 UTC, theory commented
@stefanoric If it's a connection parameter, try adding it to the target URI:

```sh
sqitch deploy "db:pg://yugabyte@127.0.0.11:5433/yugabyte? yb_silence_advisory_locks_not_supported_error=true"
```

2024-11-22 15:45 UTC, theory commented
Or try this patch:

```diff
--- a/lib/App/Sqitch/Engine/pg.pm
+++ b/lib/App/Sqitch/Engine/pg.pm
@@ -292,7 +292,13 @@ sub begin_work {
 
 # Override to try to acquire a lock on a constant number without waiting.
 sub try_lock {
-    shift->dbh->selectcol_arrayref(
+    my $self = shift;
+    # Yugabyte does not support advisory locks.
+    # https://github.com/yugabyte/yugabyte-db/issues/3642
+    # Use pessimistic locking when it becomes available.
+    # https://github.com/yugabyte/yugabyte-db/issues/5680
+    return 1 if $self->_provider ne 'postgres';
+    $self->dbh->selectcol_arrayref(
         'SELECT pg_try_advisory_lock(75474063)'
     )->[0]
 }
```

2024-11-25 09:10 UTC, stefanoric commented
It does not seem to be possible to append that command to the connection string, I get a `no matches found`.

2024-11-25 14:31 UTC, stefanoric commented
The patch did not work either, I am still getting the advisory lock error (I believe I have applied it correctly because if I put a syntax error there it breaks, so it's going through that code).

2024-11-25 17:53 UTC, theory commented
Weird. What does 

```pl
print $self->_provider, "\n";
```

output there?

2024-11-26 10:05 UTC, stefanoric commented
This is what I get: 
```
✗ sqitch deploy db:pg://yugabyte@127.0.0.11:5433/yugabyte
postgres
ERROR:  advisory locks are not yet implemented
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/3642. React with thumbs up to raise its priority
```

2024-11-26 13:44 UTC, theory commented
Okay! That shows that it's not detecting Yugabyte. We can fix that! I've opened #841 for this issue; let's move discussion there. Would you post the version you're running?

2024-11-26 15:04 UTC, FranckPachot commented
> It does not seem to be possible to append that command to the connection string, I get a `no matches found`.

other solution:
```
export PGOPTIONS="-c yb_silence_advisory_locks_not_supported_error=on"
```
before calling `sqitch`

2024-11-26 15:06 UTC, FranckPachot commented
@theory the detection is ok. With my limited perl memories, I got
```
The provider is: yugabyte
```
with
```
                    # Determine the provider. Yugabyte says this is the right way to do it.
                    # https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1653762283847589
                    my $v = $dbh->selectcol_arrayref(
                        q{SELECT split_part(version(), ' ', 2)}
                    )->[0] // '';
                    $self->_provider('yugabyte') if $v =~ /-YB-/;
                    
                    my $provider = $self->_provider();  
                    print STDERR "The provider is: $provider\n";
```

2024-11-26 15:16 UTC, theory commented
Thank you, @FranckPachot. Just need to wonder why @stefanoric gets `postgres`.

2024-11-26 15:56 UTC, stefanoric commented
```
sqitch deploy db:yugabyte://yugabyte@127.0.0.11:5433/yugabyte
The provider at line 298 is: postgres
The provider at line 150 is: yugabyte
ERROR:  advisory locks are not yet implemented
HINT:  See https://github.com/yugabyte/yugabyte-db/issues/3642. React with thumbs up to raise its priority
```

2024-11-26 16:25 UTC, stefanoric commented
> > It does not seem to be possible to append that command to the connection string, I get a `no matches found`.
> 
> other solution:
> 
> ```
> export PGOPTIONS="-c yb_silence_advisory_locks_not_supported_error=on"
> ```
> 
> before calling `sqitch`

@FranckPachot  This gets me a bit farther, but eventually, I get this:

```
✗ sqitch deploy db:pg://yugabyte@127.0.0.11:5433/yugabyte
The provider at line 298 is: postgres
The provider at line 150 is: yugabyte
Adding registry tables to db:pg://yugabyte@127.0.0.11:5433/yugabyte
"ysqlsh " failed to start: "No such file or directory"
```

I am not sure where that reference to `ysqlsh` is coming from.

2024-11-26 16:55 UTC, FranckPachot commented
`ysqlsh` is the rename of `psql` in the YugabyteDB binaries, but I guess `sqitch` is using `psql`
No idea where it comes from. Especially with a space in it `"ysqlsh "`

2024-11-26 16:58 UTC, FranckPachot commented
Maybe you have set it in `.conf` instead of `psql`?
```
[engine "pg"]
    client    = /usr/local/pgsql/bin/psql
```

2024-11-26 17:02 UTC, stefanoric commented
Ah... that was it! Some remnant of my trying things :) 

I finally got it to work. 

It's expected that it's failing, as I wanted to test reverts (since my understanding is that Yugabyte does not allow to roll back a DDL definition like Postgres does. Individual steps in Sqitch may be a good approximation.
```
sqitch deploy db:pg://yugabyte@127.0.0.11:5433/shortener
The provider at line 298 is: postgres
The provider at line 150 is: yugabyte
Adding registry tables to db:pg://yugabyte@127.0.0.11:5433/shortener
Deploying changes to db:pg://yugabyte@127.0.0.11:5433/shortener
  + initial-schema ....... ok
  + create-token-tables .. ok
  + test-error-step ...... psql:deploy/test-error-step.sql:5: ERROR:  table "tokens_unexisting" does not exist
not ok
"psql" unexpectedly returned exit value 3

Reverting all changes
  - create-token-tables .. ok
  - initial-schema ....... ok
Deploy failed
```

2024-11-26 21:32 UTC, theory commented
> ```
> sqitch deploy db:yugabyte://yugabyte@127.0.0.11:5433/yugabyte
> The provider at line 298 is: postgres
> The provider at line 150 is: yugabyte
> ERROR:  advisory locks are not yet implemented
> HINT:  See https://github.com/yugabyte/yugabyte-db/issues/3642. React with thumbs up to raise its priority
> ```

That's just wild!