Warn on sqitch add file with double extension
sqitchers/sqitch pull request #724
Opened 2023-03-16 08:55 UTC by blairjordan

- Warn on sqitch add file with double extension: `sqitch add` includes extensions for each engine. Warn if user specifies an extension resulting in a filename like `myobjects.sql.sql`

2023-03-19 22:31 UTC, theory requested changes
Handy! aCould you add a test for it in `t/add.t`?

2023-04-01 16:15 UTC, blairjordan commented on lib/App/Sqitch/Command/add.pm
> +    if ($file =~ m/\.(\w+)\.\w+$/) {
Thanks for the suggestion!

I attempted to add a test but unforunately this is my first time using Perl and I couldn't overcome this error. I expect I'm doing multiple things wrong 🙂 Any ideas what I'm doing wrong?

(output from `prove t/add.t`)

```
t/add.t .. 1/238 Can't locate object method "warning" via package "App::Sqitch::Command::add" at /usr/share/perl5/site_perl/App/Sqitch/Command/add.pm line 414.
```

2023-04-03 02:24 UTC, theory commented
Try this:

``` patch
--- a/lib/App/Sqitch/Command/add.pm
+++ b/lib/App/Sqitch/Command/add.pm
@@ -407,17 +407,17 @@ sub _add {
         file  => $file,
         error => $!
     );
-    
+
     # Warn if the file name has a double extension
     if ($file =~ m/\.(\w+)\.\1+$/) {
         my $ext = $1;
-        $self->warning(__x(
-            'Warning: file {file} has a double extension of {ext}',
+        $self->warn(__x(
+            'File {file} has a double extension of {ext}',
             file => $file,
             ext  => $ext,
         ));
     }
-    
+
     $self->info(__x 'Created {file}', file => $file);
 }
 
diff --git a/t/add.t b/t/add.t
index cd3e29a3..ea952b3d 100644
--- a/t/add.t
+++ b/t/add.t
@@ -3,7 +3,7 @@
 use strict;
 use warnings;
 use utf8;
-use Test::More tests => 238;
+use Test::More tests => 240;
 #use Test::More 'no_plan';
 use App::Sqitch;
 use App::Sqitch::Target;
@@ -414,14 +414,6 @@ EOF
         'Info should show $out created';
     unlink $out;
 
-    # # Test with file name having a double extension
-    $out = file 'test-add', 'duplicate_extension_test.sql.sql';
-    warning_is {
-        $add->_add('duplicate_extension_test.sql', $out, $tmpl, 'sqlite', 'add')
-    } [qr/double extension of sql/], 'Should get warning for file name with double extension';
-
-    unlink $out;
-    
     # Try with requires and conflicts.
     ok $add =  $CLASS->new(
         sqitch    => $sqitch,
@@ -448,6 +440,18 @@ BEGIN;
 COMMIT;
 EOF
     unlink $out;
+
+    # # Test with file name having a double extension
+    $out = file 'test-add', 'duplicate_extension_test.sql.sql';
+    $add->_add('duplicate_extension_test.sql', $out, $tmpl, 'sqlite', 'add');
+    is_deeply +MockOutput->get_info, [[__x 'Created {file}', file => $out ]],
+        'Info should show $out created';
+    is_deeply +MockOutput->get_warn, [[__x(
+        'File {file} has a double extension of {ext}',
+        file => $out,
+        ext => 'sql',
+    )]], 'Should have warned about double extension';
+    unlink $out;
 };
 
 # First, test  with Template::Tiny.
```

2023-04-08 16:21 UTC, theory approved these changes

2023-04-08 16:22 UTC, merged

2023-04-08 16:26 UTC, theory commented
Thank you!