Properly avoid advisory Yugabyte lock errors
sqitchers/sqitch pull request #847
Opened 2024-12-30 22:16 UTC by theory

The `try_lock` method was not properly checking for Yugabyte before attempting to acquire an adivosory lock. Likely it used to be a warning, but now is an error that cannot be avoided. So have `try_lock` check for Yugabyte before attempting to take an advisory lock. This requires fetching the database handle, first, as the database is not identified until it connects. So also fetch the handle earlier in `wait_lock`, just to be careful.

While at it, on Yugabyte set the
`yb_silence_advisory_locks_not_supported_error` GUC to avoid the whole issue whenever possible.

Fixes #841.

2024-12-30 22:16 UTC, theory commented
@FranckPachot how far back does Yugabyte respect the `yb_silence_advisory_locks_not_supported_error` GUC?

I don't suppose there is also a GUC to suppress errors about the use of `LOCK TABLE changes IN EXCLUSIVE MODE`?

2024-12-31 17:35 UTC, autarch requested changes
The PR description mentions setting `yb_silence_advisory_locks_not_supported_error` but I don't see that anywhere in this PR. Also, there's a change for the Oracle docs that maybe belongs in a different PR?

2024-12-31 17:35 UTC, autarch commented on lib/sqitchtutorial-oracle.pod
Did you mean to change this file as part of this PR?

2024-12-31 19:41 UTC, theory commented on lib/sqitchtutorial-oracle.pod
Yes, this was part of the fix for #845. Was not part of the original PR, but rolled in a later rebase and forgot to update the PR description.

2024-12-31 19:42 UTC, theory commented
I removed the `yb_silence_advisory_locks_not_supported_error` bit because it failed on earlier versions of Yugabyte and I couldn't figure out how to suppress the errors inside the `connected` callback.

Much obliged for the review, @autarch!

2024-12-31 19:45 UTC, autarch approved these changes
LGTM!

2024-12-31 19:58 UTC, merged

2024-12-31 21:23 UTC, FranckPachot commented
> @FranckPachot how far back does Yugabyte respect the `yb_silence_advisory_locks_not_supported_error` GUC?
> 
> I don't suppose there is also a GUC to suppress errors about the use of `LOCK TABLE changes IN EXCLUSIVE MODE`?

This GUC is only about advisory lock. There's no GUC to ignore LOCK TABLE.
It is much better to avoid calling locks rather than having them ignore ( personally, I don't like this GUC - ignoring unsupported feature)

2024-12-31 22:02 UTC, theory commented
Thanks, @FranckPachot. I ended up removing it anyway.